version: 2
jobs:
  build-n-check:
    docker:
      - image: circleci/golang:1.13.3
    steps:
      - run: |
        pwd
        ls -la .
        ls -la ..
      - checkout
      - run:
          name: Unit tests
          command: make test
      - run:
          name: Build binary
          command: make build
      - run:
          name: Acceptance tests
          command: make acceptance
  release:
    docker:
      - image: circleci/golang:1.13.3
    steps:
      - checkout
      - run:
          name: Release
          command: make release
      - store_artifacts:
          path: output/release
          destination: binaries
workflows:
  version: 2
  nightly-check:
    triggers:
      - schedule:
          cron: "50 19 * * *"
          filters:
            branches:
              only:
                - /.*/
    jobs:
      - build-n-check
  commit:
    jobs:
      - build-n-check
  build-n-release:
    jobs:
      - build-n-check:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - release:
          context: GitHub-Creds
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - build-n-check
