version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13.1
    steps:
      - checkout
      - run: echo "Hello from Test job"
  build:
    docker:
      - image: circleci/golang:1.13.1
    steps:
      - checkout
      - run: echo "Hello from Build job"
workflows:
  version: 2
  project_build:
    jobs:
      - test
      - build
