version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13.1
    steps:
      - checkout
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.13.1
    steps:
      - checkout
      - run: make build
workflows:
  version: 2
  project_build:
    jobs:
      - test
      - build
