version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3
    steps:
      - checkout
      - run: make test
      - run: make build
      - run: make acceptance
      - run: make release
#workflows:
#  version: 2
#  project_build:
#    jobs:
#      - unit-test
#      - build
